
---
- name: Install Amazon CloudWatch Agent
  ansible.builtin.yum:
    name: amazon-cloudwatch-agent
    state: present

- name: Deploy Amazon CloudWatch Agent configuration
  ansible.builtin.template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Amazon CloudWatch Agent
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: true