apiVersion: v1
kind: Service
metadata:
  name: acmecloud-app
  namespace: acmecloud
  labels:
    app: acmecloud-app
    app.kubernetes.io/name: acmecloud-app
    app.kubernetes.io/part-of: acmecloud-enterprise-platform
spec:
  type: ClusterIP
  selector:
    app: acmecloud-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
