services:

  app:
    build:
      context: ./app
    image: acmecloud-app:v1
    container_name: acmecloud-app
    restart: unless-stopped
    networks:
      - acmecloud-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  web:
    build:
      context: ./web
    image: acmecloud-web:v2
    container_name: acmecloud-web
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
        app:
          condition: service_healthy

    networks:
      - acmecloud-network

networks:
  acmecloud-network:
    driver: bridge
